name = input("请输入您的名字：")
company = input("请输入您的公司名称：")
title = input("请输入您的职位：")
phone = input("请输入您的手机号码：")
email = input("请输入您的邮箱：")
print("***************************************")
print("姓名：%s" % name)
print("公司：%s" % company)
print("职位：%s" % title)
print("电话：%s" % phone)
print("邮箱：%s" % email)
print("***************************************")
